apiVersion: apps/v1
kind: Application
metadata:
  name: myapp-test
spec:
  selector:
    matchLabels:
      app: myapp-test
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-test
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080